global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'death-tracker'
    scrape_interval: 5s
    static_configs:
      - targets: ['bot:2112']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
